### ISSUE TITLE
Erstelle Use Cases Diagramm + Detailed Use Cases  DL 08.05

### ISSUE THREAD

**Issue by Ratzz91** [Bonevski/DBLK#2]
Detailierte Beschreibung der gewünschten User-Erfahrung.

- Use Cases Diagramm
- Detailed Primary Use Cases
      - << anzeige Räume (alle) >>
      - << buche Raum >>
      - << storniere Raum >>
      - << administriere Server >> (Name ggf. noch ändern)
- Documentation

**Comment by Ratzz91** [comment]
[Use Case Diagramm.pdf](https://github.com/Bonevski/DBLK/files/8647818/Use.Case.Diagramm.pdf)
 
Hier das Use Cases Diagramm, dabei ist mir aufgefallen, dass der Admin eigentlich als "registrierter Nutzer" geführt werden kann und damit eigenständig wegfällt, was haltet ihr davon?

**Comment by Ratzz91** [comment]
[anzeige Raeume.docx](https://github.com/Bonevski/DBLK/files/8647901/anzeige.Raeume.docx)
[buche  Raum.docx](https://github.com/Bonevski/DBLK/files/8647902/buche.Raum.docx)
[storniere Raum.docx](https://github.com/Bonevski/DBLK/files/8647903/storniere.Raum.docx)
[administriere Server.docx](https://github.com/Bonevski/DBLK/files/8647904/administriere.Server.docx)

Hier die detaillierteren Primary Use Cases, gerade "administriere Server" ist  kein wirklicher Use Case mit irgendeinem sinnvollen Inhalt. Beim aufschreiben ist mir auch aufgefallen, dass wir noch über die Art der Navigation im System reden sollten, darauf muss ich den "Basic Flow" noch anpassen, auch sind die "Quality Requirements and Constraints" sehr rudimentär gehalten, da das in Firats Aufgaben fällt.

**Comment by Bonevski** [comment]
Sieht für mich gut aus, doch ich weiß nicht ob wir den Admin nicht vllt doch als extra Benutzer hinzufügen sollen, da er ja eine gesonderte Rolle in dem System spielt bzw. spielen wird. Denn so sieht es aus als würde jeder registrierte Nutzer die Möglichkeit hat auf den Use Case 'administriere Server' zugreifen kann.

Rest finde ich top

**Comment by Ratzz91** [comment]
> 
Ja deswegen fragte ich ja, habe allerdings extra im Diagramm die Authentifizierung auch beim Login angesetzt, sodass es darüber unterschieden werden kann. Wüsste nicht wie ich das eindeutiger dort markieren könnte.

**Comment by Ratzz91** [comment]
[Detailed Primary Use Cases.docx](https://github.com/Bonevski/DBLK/files/8672584/Detailed.Primary.Use.Cases.docx)

hier die überarbeitete Zusammenfassung der Detailed Primary Use Cases als eine Datei.

Gerade die "Qualitiy Requirements and Contrains" sind gefühlt sehr rudimentär. Verbesserungsvorschläge sind gerne gesehen ;)

**Comment by Ratzz91** [comment]
[Use Case Diagramm.pdf](https://github.com/Bonevski/DBLK/files/8672662/Use.Case.Diagramm.pdf)

Hier das überarbeitetes Use Case Diagramm ohne handschriftlichen Teil mit Erläuterung, ich hoffe die ist da überhaupt zulässig?

**Comment by Ratzz91** [comment]
[Dokumentation.docx](https://github.com/Bonevski/DBLK/files/8672888/Dokumentation.docx)

**Comment by Ratzz91** [comment]
Hier noch als Bilddatei
![Use Case Diagramm](https://user-images.githubusercontent.com/95695977/167938616-ef035d21-feb6-4f4a-9eb2-2d2e7eb1e3cd.png)
