### ISSUE TITLE
List of Requirements Sources (incl. Stakeholders) Deadline 6.5.22

### ISSUE THREAD

**Issue by Beppolino** [Bonevski/DBLK#3]

**Comment by Beppolino** [comment]
Deadline 6.5.

**Comment by Beppolino** [comment]
[Stakeholders.docx](https://github.com/Bonevski/DBLK/files/8647777/Stakeholders.docx)

meine Liste mit den Stackeholdern und den Anforderungen. Schaut gerne bis Dienstag, den 10.5. drüber.
Ich werde es dann am Mittwoch bis 12 mittag ins Wiki übertragen.

**Comment by Bonevski** [comment]
Die Liste find ich gut👍🏽 

Fügst du die Dateien von uns allen später zusammen zu einen und fügst sie in die Wiki hinzu, oder sollen wir jeder selber die Datei in die Wiki tun?

**Comment by Ratzz91** [comment]
kann mich da Sasha nur anschließen.
