### ISSUE TITLE
Quality Requirements & Constraints

### ISSUE THREAD

**Issue by Beppolino** [Bonevski/DBLK#4]

**Comment by Firat323** [comment]
[Qualitfy Requierments.pdf](https://github.com/Bonevski/DBLK/files/8650488/Qualitfy.Requierments.pdf)
[Quality Requierments.docx](https://github.com/Bonevski/DBLK/files/8650489/Quality.Requierments.docx)

**Comment by Firat323** [comment]
habe zu 2 Sachen nicht wirklich Ahnung was ich da schreiben soll deshalb falls einem dazu was einfällt bitte bescheid sagen oder ob ihr das in der Tabellen form haben wollt wie in der Vorlesung

**Comment by Ratzz91** [comment]
[Quality.Requierments.docx](https://github.com/Bonevski/DBLK/files/8672312/Quality.Requierments.docx)

Ich kam nicht dazu früher reinzugucken, habe da gerade paar Sachen korrigiert, Sry hätte es eigentlich gerne per Korrekturfunktion zurückgeschickt, aber uns läuft jetzt die Zeit weg. Bei dir in der Datei ist ein Schatten hinter der Schrift den ich nicht entfernt bekomme. 

Wartbarkeit habe ich etwas reingeschrieben, zur Übertragbarkeit wüsste ich gerade auch nichts.
