### ISSUE TITLE
Visualization of System Vision + Context 06.05

### ISSUE THREAD

**Issue by Ratzz91** [Bonevski/DBLK#5]
drei Sätze Problem / Solution / Value

**Comment by Bonevski** [comment]
06.05 Abgabe

**Comment by Bonevski** [comment]
*Raumbuchungssystem*

**Comment by Bonevski** [comment]
[System Vision.docx]
(https://github.com/Bonevski/DBLK/files/8626501/System.Vision.docx)

Dokument erstellt. Text + Grafik eingefügt

Deadline 11.05

**Comment by Bonevski** [comment]
Vorgehensweise:

Zu Beginn wurde sich die zu lösende Problematik angeschaut und diskutiert. Dann überlegte man wie man mithilfe des Raumbuchungssystem dies verbessern bzw. lösen kann. Dabei wurde nicht nur auf ein Nutzer/User wert gelegt sondern versucht es mehr für die Hochschule zu verallgemeinern. Bedeutet wir nicht nur die Studierenden sondern auch die Dozenten/Mitarbeiter der Fachhochschule ein Nutzen aus dem System ziehen können.

Bei der Grafik wurde sich an das Beispiel der Vorlesung orientiert, da diese große Ähnlichkeiten mit dem Raumbuchungssystem hat. In der Grafik selber wurden kleine Anpassungen vorgenommen, damit sich die Grafik auf unser Projekt bezieht.

**Comment by Ratzz91** [comment]
Ich hab mir gerade das System Vision nochmal angesehen, bin nicht sicher wie das genau definiert war, aber wenn was im Kreis ist müssen wir doch auch aktiv Bezug darauf nehmen und es integrieren oder? Müssten dann nicht "Documents.." und "external Systems" außerhalb des Kreises sein, sodass wir wissen dass sie existieren aber hier in unserem Beispiel wir nicht damit interagieren?
