### ISSUE TITLE
Domänenmodell 

### ISSUE THREAD

**Issue by Ratzz91** [Bonevski/DBLK#6]
To Do:
- UML Klassendiagramm
- Dokumentation Klassendiagramm

**Comment by Beppolino** [comment]
hast du schon was hochgeladen? Ich seh hier nix, oder ist das im Wiki?

**Comment by Ratzz91** [comment]
Ne gerade erst die erste Datei hochgeladen, will den Issue aber eigentlich löschen, da er entweder in Use Cases als Aufgabe oder unter den Dokumentations-Issue gehört. Hab nur bisher keine Löschfunktion gefunden.
